# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inscrirerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWidget(object):
    def setupUi(self, registerWidget):
        registerWidget.setObjectName("registerWidget")
        registerWidget.resize(912, 636)
        self.label = QtWidgets.QLabel(registerWidget)
        self.label.setGeometry(QtCore.QRect(250, 120, 401, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(registerWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 250, 424, 144))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.usernameLine.setMinimumSize(QtCore.QSize(200, 30))
        self.usernameLine.setObjectName("usernameLine")
        self.verticalLayout.addWidget(self.usernameLine)
        self.emailLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.emailLine.setMinimumSize(QtCore.QSize(200, 30))
        self.emailLine.setObjectName("emailLine")
        self.verticalLayout.addWidget(self.emailLine)
        self.passwordLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordLine.setMinimumSize(QtCore.QSize(200, 30))
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.verticalLayout.addWidget(self.passwordLine)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.gobackButton = QtWidgets.QPushButton(registerWidget)
        self.gobackButton.setGeometry(QtCore.QRect(700, 530, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.gobackButton.setFont(font)
        self.gobackButton.setObjectName("gobackButton")

        self.retranslateUi(registerWidget)
        self.pushButton.clicked.connect(registerWidget.register)
        self.gobackButton.clicked.connect(registerWidget.goback)
        QtCore.QMetaObject.connectSlotsByName(registerWidget)

    def retranslateUi(self, registerWidget):
        _translate = QtCore.QCoreApplication.translate
        registerWidget.setWindowTitle(_translate("registerWidget", "Form"))
        self.label.setText(_translate("registerWidget", "S\'INSCRIRER"))
        self.label_2.setText(_translate("registerWidget", "Nom Complet:"))
        self.label_4.setText(_translate("registerWidget", "Adresse Email:"))
        self.label_3.setText(_translate("registerWidget", "Mot De Passe:"))
        self.pushButton.setText(_translate("registerWidget", "S\'inscrirer"))
        self.gobackButton.setText(_translate("registerWidget", "Retourner"))
